# Generated by Django 3.2.12 on 2022-03-16 20:11

from django.db import migrations
import vditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myzoneapp', '0005_auto_20220316_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=vditor.fields.VditorTextField(default=''),
        ),
    ]
