# Generated by Django 3.2.12 on 2022-03-17 11:21

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('myzoneapp', '0006_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='avatar',
            field=models.ImageField(null=True, upload_to=pathlib.PurePosixPath('/workspace/uploads')),
        ),
    ]
