# Generated by Django 3.2.12 on 2022-03-17 17:33

from django.db import migrations, models
import django.db.models.deletion
import vditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myzoneapp', '0010_auto_20220317_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('profile', vditor.fields.VditorTextField(default='')),
            ],
        ),
    ]
