# Generated by Django 3.2.12 on 2022-03-17 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myzoneapp', '0011_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile',
            new_name='content',
        ),
    ]
