# Generated by Django 3.2.12 on 2022-03-22 11:21

from dataclasses import field
from django.db import migrations, models
from django.forms import CharField


class Migration(migrations.Migration):

    dependencies = [
        ('myzoneapp', '0015_post_draft'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'default_manager_name': 'objects'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_en'
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='name_en'
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=15, default='', blank=True)
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=15, default='', blank=True)
        ),
        migrations.AddField(
            model_name='category',
            name='name_zh',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_zh',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
