# Generated by Django 3.2.12 on 2022-03-22 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myzoneapp', '0017_alter_tag_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_zh',
            new_name='name_zh_CN',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='name_zh',
            new_name='name_zh_CN',
        ),
    ]
