# Generated by Django 3.2.12 on 2022-03-22 14:19

from django.db import migrations
import vditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myzoneapp', '0019_auto_20220322_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'default_manager_name': 'objects'},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='content',
            new_name='content_en',
        ),
        migrations.AddField(
            model_name='profile',
            name='content_zh_cn',
            field=vditor.fields.VditorTextField(default=''),
        ),
    ]
