# Generated by Django 3.2.12 on 2022-04-20 13:58

from django.db import migrations, models
import vditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myzoneapp', '0020_auto_20220322_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('publication_type', models.CharField(choices=[(None, 'Unknown'), ('article', 'Journal Article'), ('book', 'Book (Chapter)'), ('conference', 'Conference Proceeding')], default='article', max_length=10)),
                ('authors', models.CharField(max_length=255)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='publication_covers')),
                ('publisher', models.CharField(max_length=255)),
                ('publish_date', models.DateField(blank=True)),
                ('volume', models.PositiveSmallIntegerField(blank=True)),
                ('issue', models.PositiveSmallIntegerField(blank=True)),
                ('edition', models.PositiveSmallIntegerField(blank=True)),
                ('page_start', models.PositiveSmallIntegerField(blank=True)),
                ('page_end', models.PositiveSmallIntegerField(blank=True)),
                ('abstract', vditor.fields.VditorTextField(default='')),
            ],
        ),
    ]
