# Generated by Django 3.2.12 on 2022-04-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myzoneapp', '0021_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='edition',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='issue',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='page_end',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='page_start',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='volume',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
