# Generated by Django 3.2.12 on 2022-04-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myzoneapp', '0022_auto_20220420_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
