# Generated by Django 3.2.12 on 2022-04-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myzoneapp', '0024_publication_doi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='page_end',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='page_start',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
