# Generated by Django 3.2.12 on 2022-05-02 18:26

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myzoneapp', '0025_auto_20220421_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='covers'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='cover',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='publication_covers'),
        ),
    ]
