# Generated by Django 3.2.12 on 2022-07-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myzoneapp', '0027_auto_20220725_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttranslate',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('zh-hans', 'Chinese')], max_length=7),
        ),
    ]
