# Generated by Django 3.2.12 on 2022-07-26 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myzoneapp', '0028_alter_posttranslate_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_zh_cn',
            new_name='name_zh_hans',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='name_zh_cn',
            new_name='name_zh_hans',
        ),
    ]
