# Generated by Django 3.2.12 on 2022-07-26 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myzoneapp', '0029_auto_20220726_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='content_zh_cn',
            new_name='content_zh_hans',
        ),
    ]
